# Generated by Django 5.2.10 on 2026-01-23 04:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Es Administrador"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LawCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_interno",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código Interno"
                    ),
                ),
                ("caratula", models.CharField(max_length=500, verbose_name="Carátula")),
                (
                    "nro_expediente",
                    models.CharField(
                        max_length=100, verbose_name="Número de Expediente"
                    ),
                ),
                (
                    "juzgado",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Juzgado"
                    ),
                ),
                (
                    "fuero",
                    models.CharField(
                        default="Civil", max_length=50, verbose_name="Fuero"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Abierto", "Abierto"),
                            ("En Trámite", "En Trámite"),
                            ("Pausado", "Pausado"),
                            ("Cerrado", "Cerrado"),
                        ],
                        default="Abierto",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "abogado_responsable",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Abogado Responsable"
                    ),
                ),
                (
                    "cliente_nombre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Cliente"
                    ),
                ),
                (
                    "cliente_dni",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="DNI/RUC Cliente"
                    ),
                ),
                (
                    "contraparte",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contraparte"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente",
                "verbose_name_plural": "Expedientes",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "etiqueta",
                    models.CharField(
                        choices=[
                            ("Estrategia", "Estrategia"),
                            ("Documentación", "Documentación"),
                            ("Investigación", "Investigación"),
                            ("Jurisprudencia", "Jurisprudencia"),
                        ],
                        default="Estrategia",
                        max_length=50,
                        verbose_name="Etiqueta",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="api.lawcase",
                        verbose_name="Expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("resumen", models.TextField(blank=True, verbose_name="Resumen")),
                ("hora", models.TimeField(blank=True, null=True, verbose_name="Hora")),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de Vencimiento"),
                ),
                (
                    "cumplida",
                    models.BooleanField(default=False, verbose_name="Cumplida"),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("Alta", "Alta"),
                            ("Media", "Media"),
                            ("Baja", "Baja"),
                        ],
                        default="Media",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Cumplimiento"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_completed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completada por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="api.lawcase",
                        verbose_name="Expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["fecha_vencimiento", "prioridad"],
            },
        ),
        migrations.CreateModel(
            name="CaseActuacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "tipo",
                    models.CharField(
                        default="Escrito", max_length=100, verbose_name="Tipo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actuaciones_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actuaciones",
                        to="api.lawcase",
                        verbose_name="Expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actuación",
                "verbose_name_plural": "Actuaciones",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lawcase",
            index=models.Index(
                fields=["codigo_interno"], name="api_lawcase_codigo__995206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lawcase",
            index=models.Index(fields=["estado"], name="api_lawcase_estado_bc88ed_idx"),
        ),
        migrations.AddIndex(
            model_name="lawcase",
            index=models.Index(
                fields=["-updated_at"], name="api_lawcase_updated_bc6cc1_idx"
            ),
        ),
    ]
