# Generated by Django 4.2 on 2026-03-14 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_aviso"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawcase",
            name="abogados_asignados",
            field=models.ManyToManyField(
                blank=True,
                related_name="cases_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Abogados Asignados",
            ),
        ),
    ]
