# Generated by Django 4.2 on 2026-03-14 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_migrate_abogado_responsable_to_abogados_asignados"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStickyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("contenido", models.TextField(blank=True, verbose_name="Contenido")),
                (
                    "fecha_recordatorio",
                    models.DateField(blank=True, null=True, verbose_name="Recordar el"),
                ),
                ("completada", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notita",
                "verbose_name_plural": "Notitas",
                "ordering": ["orden", "-fecha_recordatorio", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userstickynote",
            index=models.Index(fields=["user"], name="api_usersti_user_id_496041_idx"),
        ),
        migrations.AddIndex(
            model_name="userstickynote",
            index=models.Index(
                fields=["user", "completada"], name="api_usersti_user_id_6b3a86_idx"
            ),
        ),
    ]
