# Generated by Django 4.2 on 2026-03-14 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_userstickynote"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("hora", models.TimeField(blank=True, null=True, verbose_name="Hora")),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Reunión, Cita, Recordatorio",
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_calendar_events",
                        to="api.lawcase",
                        verbose_name="Expediente (opcional)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de calendario",
                "verbose_name_plural": "Eventos de calendario",
                "ordering": ["fecha", "hora"],
            },
        ),
        migrations.AddIndex(
            model_name="usercalendarevent",
            index=models.Index(fields=["user"], name="api_usercal_user_id_cbc6fb_idx"),
        ),
        migrations.AddIndex(
            model_name="usercalendarevent",
            index=models.Index(
                fields=["user", "fecha"], name="api_usercal_user_id_f388fa_idx"
            ),
        ),
    ]
